language: android

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

android:
  components:
    - tools
    - platform-tools
    - android-25
    - build-tools-25.0.1
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle